# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icuvisor < Formula
  desc "MCP server connecting intervals.icu training data to AI assistants."
  homepage "https://icuvisor.dev"
  version "0.1.1"
  license "MIT"

  on_macos do
    url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.1/icuvisor_0.1.1_macos_universal.tar.gz"
    sha256 "67d6cd6d542be81d6f237f1cad1324a05dd2b47daa45ad13d5c873097da75e5b"

    define_method(:install) do
      bin.install "icuvisor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.1/icuvisor_0.1.1_linux_amd64.tar.gz"
      sha256 "fe24de4eac4964b39e7584640605dc4c8517c1ae13a7ea374df9e96c6807b982"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.1/icuvisor_0.1.1_linux_arm64.tar.gz"
      sha256 "252291f6af5534724d07d72c6d6d4594a0bba3c91217368c30478805f08eb39f"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
  end

  def caveats
    <<~EOS
      Run `icuvisor setup` once to store your intervals.icu API key in the
      system keychain, then point your MCP client at the `icuvisor` binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/icuvisor version")
  end
end
