# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icuvisor < Formula
  desc "MCP server connecting intervals.icu training data to AI assistants."
  homepage "https://icuvisor.app"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/ricardocabral/icuvisor/releases/download/v1.0.0/icuvisor_1.0.0_macos_universal.tar.gz"
    sha256 "56f61486e5af5580e32974e55db7eb0c7312acf3e4b6920963497ab28ace9f8b"

    define_method(:install) do
      bin.install "icuvisor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v1.0.0/icuvisor_1.0.0_linux_amd64.tar.gz"
      sha256 "ee073774bc8cf71195263bcf129aaa68343bde10f5c32611881cd894112f8104"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v1.0.0/icuvisor_1.0.0_linux_arm64.tar.gz"
      sha256 "7296af5246f845c433e2f2f604068606b1909f43b40067a91cdc5a4896f09ea2"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
  end

  def caveats
    <<~EOS
      Run `icuvisor setup` once to store your intervals.icu API key in the
      system keychain, then point your MCP client at the `icuvisor` binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/icuvisor version")
  end
end
