# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icuvisor < Formula
  desc "MCP server connecting intervals.icu training data to AI assistants."
  homepage "https://icuvisor.app"
  version "0.1.5"
  license "MIT"

  on_macos do
    url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.5/icuvisor_0.1.5_macos_universal.tar.gz"
    sha256 "bb30d6a686a81b93f7906dffec7c6ced30dfe98442b909f932e217e39b92daae"

    define_method(:install) do
      bin.install "icuvisor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.5/icuvisor_0.1.5_linux_amd64.tar.gz"
      sha256 "e4a82a29e0db3b7768c2d885a64b189c3bcd03b6a35f462c6809467d7d3ba4f1"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.5/icuvisor_0.1.5_linux_arm64.tar.gz"
      sha256 "94c297346bcd1e485475aa74bf20f07e00e7905dc18741dec0437fc4db69e62a"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
  end

  def caveats
    <<~EOS
      Run `icuvisor setup` once to store your intervals.icu API key in the
      system keychain, then point your MCP client at the `icuvisor` binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/icuvisor version")
  end
end
